### PR TITLE
feat: add case-insensitive search

### PR DESCRIPTION
**Pull request by Nadzt**
made the searchbar case insensitive by making both values lowercase

### CODE REVIEW

**Comment by fwpp** [comment]
Function is good!

For the commit message, it will be better that use `feat: add case-insensitive search` as title without the body. When checking the git log, we can know what the commit did with the title only more easier.

Please run `yarn lint:check`. There is lint error of the changes.

```diff
--- a/src/components/DataPanel/DataPanel.tsx
+++ b/src/components/DataPanel/DataPanel.tsx
@@ -54,7 +54,8 @@ function DataPanel(props: Props) {
       .map((isHidden: boolean, idx: number) => {
         if (isHidden) return true;
         return !Object.values(ramenStores[idx])
-          .join().toLowerCase()
+          .join()
+          .toLowerCase()
```

**Comment by fwpp** [comment]
Close #23

**Comment by ss8651twtw** [comment]
@Nadzt Thanks for the contribution!
Just a reminder, it should be "case insensitive" not "case sensitive".
Please correct the commit message and PR / issue submission information.

**Comment by Nadzt** [comment]
You're right, thanks for the feedback :)
it was my first contribution, so i was a little confused with the steps i had to follow, i ran lint:check and commited the changed already.

**Review by fwpp — APPROVED** [review]
Thank you for the contribution!

**Review by ss8651twtw — APPROVED** [review]
LGTM

**Pull request merged**
